### ISSUE TITLE
Typo in resume

### ISSUE THREAD

**Issue by yoursunny** [sankalpatimilsina12/sankalpatimilsina12.github.io#1]
The resume has a typo: *Amazon Web System* should be *Amazon Web Services*.

Moreover, when I attempted to report this via contact form on the website, it says "something went wrong".
Browser: Chrome on iOS 15.5.

**Comment by sankalpatimilsina12** [comment]
Thank you for your feedback Junxiao. I fixed the typo. Yeah, the contact form needs some work, it's broken now.
